#include<iostream>
#include<conio.h>
using namespace std;

int main ()
{
    char ch;
    int num1,num2,sum;
    cout<< "enter your name here : ";


    cin>>ch>>sum;


    cout<< "entered caracter is : "<<ch<<sum;
           #include<iostream>
             #include<conio.h>
                              using namespace std;

                               int main()
                                                                                   {
char c        h      ;
               cout<< "Enter an character   : ";
                      cin>> ch;
c                                       out<<"Entered chacarter is :" <<ch;
    getch();
                                    }#include<iostream>
#include<conio.h>
using namespace std;

int main()
{
char ch;
cout<< "Enter an character   : ";
cin>> ch;
cout<<"Entered chacarter is :" <<ch;
    getch();
}#include<iostream>
#include<conio.h>
using namespace std;

int main()
{
char ch;
cout<< "Enter an character   : ";
cin>> ch;
cout<<"Entered chacarter is :" <<ch;
    getch();
}
    getch();



}


